server:
  port: 8007

spring:
  application:
    name: sms-service
  redis:
    host: 127.0.0.1
    port: 6379

  cache:
    redis:
      cache-null-values: false
      time-to-live: 14400

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
