server:
  port: 8007

spring:
  application:
    name: sms-service
  cache:
    type: redis

  redis:
    clientName: MMKamal
    host: localhost
    port: 6379


eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
