
server:
  port: 8004

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:9040/mmkamal
    username: postgres
    password: ${password}
  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always


security:
  jwt:
    uri: /api/v1/auth/**
    authUri: /users/login
    expiration: 86400
    secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY


flyway:
  url: jdbc:postgresql://localhost:9040/mmkamal
  username: postgres
  password: ${password}
  schemas: mmkamal