server:
  port: 8072

spring:
  application:
    name: gateway-service

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.javatab: DEBUG

security:
  jwt:
    uri: /api/v1/auth/**
    authUri: /users/login
    expiration: 86400
    secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    routes:
      enabled: true
#zuul:
#  sensitive-headers: Cookie,Set-Cookie
#  routes:
#    auth-server:
#      path: /api/v1/auth/users/**
#      url: http://localhost:8004/api/v1/auth/users
#    sms-server:
#      path: /api/v1/sms/**
#      url: http://localhost:8007/api/v1/sms
#
#ribbon:
#  ReadTimeout: 60000